ocdp:
  security:
      username: ocdp
      password: Passw0rd
  etcd:
     endpoint: http://103.235.243.145:2379
  ldap:
      url: ldap://ochadoop06.jcloud.local
      userDN: cn=root,dc=asiainfo,dc=com
      password: 00AAaa00
      base: dc=asiainfo,dc=com
  krb:
      kdcHost: ochadoop06.jcloud.local
      user-principal: admin/admin@ASIAINFO.COM
      keytab-location: /tmp/admin.keytab
      adminPwd: 00AAaa00
      realm: ASIAINFO.COM
  ranger:
      rangerUri: http://ocdpbroker.jcloud.local:6080
      rangerUser: admin
      rangerPwd: admin
  hdfs:
      hdfsSuperUser: hdfs-OCDP@ASIAINFO.COM
      userKeytab: /Users/baikai/Work/Dev/AsiaInfo/hadoopConf/hdfs.keytab
      krbFilePath: /Users/baikai/Work/Dev/AsiaInfo/hadoopConf/krb5.conf
      hdfsURL: hdfs://ocdpbroker.jcloud.local


