ocdp:
  security:
      username: username
      password: password
  etcd:
     endpoint: etcdEndpoint
  ldap:
      url: ldapServerURL
      userDN: userdn
      password: password
      base: base
  krb:
      kdcHost: kdcHost
      user-principal: krbUserPrincipal
      keytab-location: krbAdminKeytab
      adminPwd: password
      realm: realm
  ranger:
      rangerUri: rangerUri
      rangerUser: admin
      rangerPwd: admin
  hdfs:
      hdfsSuperUser: hdfsSuperUserPrincipal
      userKeytab: userKeytab
      krbFilePath: krb5File
      hdfsURL: hdfsURL


